### ISSUE TITLE
M2 Version 1.9.1

### ISSUE THREAD

**Issue by b-stone** [b-stone/Visualize-M2#103]
@bbarwick, Mike would like Visualize in version 1.9.1. This means we need our package to be mostly documented and working somewhat working by June 2 (June 3 is the release date, see 
[https://github.com/Macaulay2/M2/milestones](https://github.com/Macaulay2/M2/milestones)). 
So we should make milestones on issues we would like to push out by June 2.

**Comment by bbarwick** [comment]
Wow, June 2nd is soon.  @b-stone Can we still publish a version of the package in JSAG if we go ahead and include an initial release in the next M2 release?

**Comment by b-stone** [comment]
Yes. He said to go ahead and push it even if it is not fully ready. Submission to JSAG and incorporation to M2 are separate things. I have marked some items I would like to fix by then. If you are busy with life and things, don't feel you need to work on this. I just happen to have time this week and I will be making this my main focus.

**Comment by bbarwick** [comment]
I will have a lot of time to work on this.  This deadline is good motivation to push us to get as much implemented as we can over the next week.  Is there an easy way for us to communicate this week about what we're working on?  Google something?

**Comment by b-stone** [comment]
@bbarwick, before we submit a pull request, I think we should update the version number, say version 0.8, and create a new branch. Once on the new branch, we can take care of issues #2, #3, #4, and #5. This way the master branch is the development branch and we will have a version history of what we submitted. What do you think?

**Comment by bbarwick** [comment]
@b-stone I'm fine with that.  I updated the version number to 0.8, and we can minify all of our js, css, and html files for the release branch.  Should we use the master-stable branch for this or create one specifically for this version of the package?

**Comment by b-stone** [comment]
I like the idea of making a branch just for this version. We can delete all the unneeded files on the branch and just do a copy paste to the M2 repo. Dan will only want what is needed to make the program run. That is `/Visualize/` and `Visualize.m2`. We should make this happen by Tuesday.

**Comment by bbarwick** [comment]
I created a new branch called M2-1.9.1-Release that has pretty much the barebones files necessary for the methods to run.  It might be hard to merge to this branch because it doesn't have a lot of the files that are on the master branch.  Or maybe it will be easy to merge to... if only I fully understood how git merge manages conflicts.

**Comment by bbarwick** [comment]
Actually this new branch has some edits to Visualize.m2 that might be good to add to the master branch (contact information for authors and some cleaned up comments and methods).  How can we just merge a single file from one branch to another?

**Comment by b-stone** [comment]
Yes you can. I believe checkout will do that. I can do this tomorrow if you want.

**Comment by b-stone** [comment]
So I did this and it seems to work. Here is what I did. To do this just switch the the branch you want to merge to, in this case master:

```git checkout master```

then checkout the file you want to the branch with this:

```git checkout M2-1.9.1-Release Visualize.m2```

This should take the latest changes from the M2-1.9.1-Release branch and merge them into master.

**Comment by b-stone** [comment]
I think we might be done. I have merged the needed files to the release branch, updated the ideal stuff, added the documentation. It seems to work for me. You should test it out.

**Comment by b-stone** [comment]
So it is done!

[https://github.com/Macaulay2/M2/pull/476](https://github.com/Macaulay2/M2/pull/476)
