### ISSUE TITLE
Give options to export graph/digraph constructors to an external file.

### ISSUE THREAD

**Issue by bbarwick** [b-stone/Visualize-M2#11]
Give options to either export to a new file or to append to a fixed file?

**Comment by b-stone** [comment]
I am not opposed to this. But I do think the user can do this if they want to with the current M2 methods.

**Comment by bbarwick** [comment]
@b-stone How are you thinking of the user being able to do this currently?

**Comment by b-stone** [comment]
M2 has a bunch of file manipulators in place, see `http://www.math.uiuc.edu/Macaulay2/doc/Macaulay2-1.7/share/doc/Macaulay2/Macaulay2Doc/html/___File.html`. If the user wants, they can create a file and use `<<` to push information there just like they would any other package. 

But we do have an option in visualize (it's currently broken, see Issue #25) the moves the html files into a specified location. We could see about adding file output as well. But the output would just be a hash table and is returned to M2 when the user ends the session in the browser (this process is somewhat explained in Issue #21; try running the code there).

**Comment by b-stone** [comment]
solved with server communication.
