### ISSUE TITLE
isLattice issue on server communication

### ISSUE THREAD

**Issue by b-stone** [b-stone/Visualize-M2#112]
@bbarwick, the menu items are not correct in Poset. See here: 

![image](https://cloud.githubusercontent.com/assets/1364138/15635615/3601fa00-25b1-11e6-8b32-59ac1737a0b0.png)

**Comment by bbarwick** [comment]
Those methods (like isAtomic) require a lattice for them to make sense, not just a poset, so I have them check whether it is a lattice first and then used "Not lattice." to basically mean that the test is not applicable.

**Comment by b-stone** [comment]
Sounds good to me. I was just checking.
