### ISSUE TITLE
Deleting edges/relations in posets

### ISSUE THREAD

**Issue by bbarwick** [b-stone/Visualize-M2#129]
I just noticed that apparently deleting relations in posets doesn't work at all.  Oops.  I'll work on this.

**Comment by b-stone** [comment]
Oh dear. Well when you fix it just push the changes the `M2-1.9.1-Release` (most annoying branch name to type) branch and then add the file to the `add-visualize` branch here 

[https://github.com/b-stone/M2](https://github.com/b-stone/M2)

You might need to accept the invitation to be a collaborator in your email. The way I would do this is to clone the repo and then just copy/paste the new file in. I think git will recognize the difference. I think.

**Comment by bbarwick** [comment]
This was a simple fix once I looked at it, so I just pushed it directly to the master branch.  I don't really know the best way to add the new file to the add-visualize branch, but I'm sure they have already pulled it into the M2 repo anyway.

**Comment by b-stone** [comment]
It has been pulled already. I can submit a new request, or we can just accept the bug. Version 2.0 is due out in October. We can submit the best version then.
