### ISSUE TITLE
Export incidence and adjacency matrices as sparse matrices to condense output.

### ISSUE THREAD

**Issue by bbarwick** [b-stone/Visualize-M2#13]
See second example on http://www.math.uiuc.edu/Macaulay2/doc/Macaulay2-1.5/share/doc/Macaulay2/Macaulay2Doc/html/_map_lp__Module_cm__Module_cm__List_rp.html to see how to input sparse matrices.

**Comment by b-stone** [comment]
We decided we don't need this anymore. Will open if we change our mind.
