### ISSUE TITLE
Make things look Good

### ISSUE THREAD

**Issue by b-stone** [b-stone/Visualize-M2#14]
We need the following template to look nice:

`Visualize-M2/Visualize/templates/visGraph/visGraph-example-for-jim.html`

1. eliminate links on top and make one "toolbox" of links (possibly on the side?);
2. Eliminate the stuff on the bottom and replace them with a "copy M2 code to clipboard" and "download M2 code" options (possibly putting them in the toolbox above?)
3. get rid of 3D option. This is just weird and not needed right now. 
3. any other improvement that the cool kids would do.
3. currently when the edit mode is on, the text gets hi-lighted wend creating edges. Can we get rid of this feature?

**Comment by vlandham** [comment]
so there are two graphs on the page. the top one seems to be broken? or
else I'm having problems editing it or doing anything with it.

Are we keeping both graphs on the page?

By 'toolbox' do you just mean like a panel of options? are there more
options to be added - or will this be it?

Could you clarify what "the stuff on the bottom" is. Is it the 2nd graph?
is it the text between the first graph and the second one? again are we
keeping both?

**Comment by b-stone** [comment]
Not sure about the two graph issue. For some reason it did that when I saved the file. I will make a new file. 

Yes to the panel of options. We will be adding more stuff to it as well.

The stuff at the bottom is the following: 

Macaulay2 Constructor: graph({{x_1, x_0}, {x_3, x_0}, {x_3, x_1}, {x_4, x_0}, {x_2, x_3}}, Singletons => {x_5})

Incidence Matrix: matrix{{1,1,0,1,0},{1,0,1,0,0},{0,1,1,0,1},{0,0,0,1,0},{0,0,0,0,1},{0,0,0,0,0}}

Adjacency Matrix: matrix{{0,1,1,1,0,0},{1,0,1,0,0,0},{1,1,0,0,1,0},{1,0,0,0,0,0},{0,0,1,0,0,0},{0,0,0,0,0,0}}

These lines should be the end of the page. We are going not have the incidence matrix and adjacency matrix stuff. We would like the Macaulay2 Constructor code, i.e.

`graph({{x_1, x_0}, {x_3, x_0}, {x_3, x_1}, {x_4, x_0}, {x_2, x_3}}, Singletons => {x_5})`

available. Preferable in the form of a "save to the clipboard" button and a "download to file" button.

**Comment by b-stone** [comment]
look at `for-jim-corrected.html` with the directory `/js/`.

**Comment by b-stone** [comment]
I am going to close this.
