### ISSUE TITLE
Make the color of ideal2d not look like vomit. 

### ISSUE THREAD

**Issue by b-stone** [b-stone/Visualize-M2#141]

**Comment by tenkosky** [comment]
You tell me what colors you want and I'll use them, http://htmlcolorcodes.com/  

I have a feeling if I just pick colors at random, you won't like them.

**Comment by vlandham** [comment]
check out : http://colorbrewer2.org/
and
http://tools.medialab.sciences-po.fr/iwanthue/

for color options

**Comment by b-stone** [comment]
Thanks Jim. I think the color looks better now.
