### ISSUE TITLE
issue with highlight comparable elements

### ISSUE THREAD

**Issue by tenkosky** [b-stone/Visualize-M2#144]
The Highlight comparable elements tool for posets does not work properly for many examples.

**Comment by tenkosky** [comment]
The issue seems to be only occurring when you add vertices and relations in the browser.  The image that's wrong was the one where I edited it in the browser.  I then defined the same poset in M2 and when visualized it seems to work.

<img width="611" alt="screen shot 2017-09-22 at 5 17 31 pm" src="https://user-images.githubusercontent.com/8619558/30765389-778b24c4-9fbd-11e7-9b1f-72335fe3d4b2.png">
<img width="566" alt="screen shot 2017-09-22 at 5 17 40 pm" src="https://user-images.githubusercontent.com/8619558/30765392-792693d6-9fbd-11e7-8e07-bbc15ac47200.png">

**Comment by bbarwick** [comment]
@tenkosky I can probably work it out from the pictures, but it might be faster if you could tell me:
1. Can you copy/paste the poset that you started with in M2?
2. What modifications did you make to it in the browser? (i.e., which elements/relations did you add?)
3. Which element are you clicking on in each picture and telling it to highlight the comparable elements?

There's probably something silly happening when the covering relations are being updated after editing the poset in the browser.  Your example would give me a good test case for seeing if I've fixed it.

**Comment by tenkosky** [comment]
1. I started with the poset in the example on the Macaulay2 website:
P=poset{{1,2},{2,3},{3,4},{3,6},{5,6},{6,7}}.
2. I just added new nodes and relations at random and got the poset in my screenshot above.  The order in which I added the vertices is labeled but I don't remember the order in which I added the relations.  The issue seems to happen with any poset I start with once I add enough edges and relations.
3. In both pictures I clicked on vertex 3.  The relation {1,11} should not be highlighted in the first.

**Comment by tenkosky** [comment]
hmm.  I can't seem to replicate the problem with that poset.  maybe there was an issue with my browser

**Comment by bbarwick** [comment]
Thanks for the extra information.  I'll play around with it and see if I can replicate the issue.

**Comment by bbarwick** [comment]
This issue was most likely caused by a typo in the visPoset.js code for editing nodes and relations.  These typos were corrected in pull request #156, so the issue should be resolved now.  Feel free to reopen the issue if it pops back up.
