### ISSUE TITLE
Merge the side menu with each visualization template

### ISSUE THREAD

**Issue by bbarwick** [b-stone/Visualize-M2#20]
Need to merge the side menu with the following templates:
visDigraph
visPoset
visSimplicialComplex2d
visSimplicialComplex3d (when written)

**Comment by b-stone** [comment]
I noticed that no matter what graph you use, the same graph is displayed with visGraph.

**Comment by b-stone** [comment]
I added some the labels in to the `visGraph-template.html` and commented out the data set. If you want, you can remove this for your testing.

**Comment by b-stone** [comment]
I think all is done except for simplicial complex. I created issue #99 for this and will close this one.
