### ISSUE TITLE
Server communication

### ISSUE THREAD

**Issue by b-stone** [b-stone/Visualize-M2#21]
We need to make the M2 server talk to the browser. A concept works right now and will be posted soon. The files are currently in the Workshop repo. Things we would like:

1. Export edited info to M2. With this export, we will need a format. Maybe a HashTable?
2. Give the user an option to copy information to a clipboard
3. make option to not open port.

**Comment by b-stone** [comment]
Before the workshop ended, I merged a working server to the repo. To make it work you need to do the following:

> restart
> loadPackage"Visualize"
> G = graph({{0,1},{0,3},{0,4},{1,3},{2,3}},Singletons => {5})
> listener = openPort("$:8000")
> visualize G -- this opens browser; come back and run openServer to start communication.
> H = openServer(listener)
> H
> closePort("$:8000")

I think this is correct If you want to play with the newest stuff you will need to checkout on branch `server-workflow`.

As to the actual workflow, here is an idea. I lifted this from the comments in `Visualize.m2`. 

>  The idea here is to open a port using a number from the config file. 
>  Then we assign a global varable portTest = true. This way we can test
>  if the port is open or not. Ideally this method would not have a input
>  but would pull the info from the config file. 
>  
>  The work flow would be, 
>  1. Do cool VisStuff; 
>  2. openPort() and then continue (with the same webpage) your work;
>  3. End session to export info to browser;
>  4. closePort() (or restart M2; not sure if this works) to end.
> 
>  At first I thought it would probably be better to have 2 and 4 in all 
>  the methods and have a test to see if 2 needs an action (with global 
>  var portTest), and an option that lets the user decide if the port 
>  should stay open. But now I think it would be better if the user actually
>  opens the port. This would give more control to the user.

**Comment by b-stone** [comment]
I think I have a workflow I like. What do you think about this @bbarwick ?

> restart
> loadPackage"Visualize"
> openPort("$:8000") -- User opens port
> G = graph({{0,1},{0,3},{0,4},{1,3},{2,3}},Singletons => {5})
> H = visualize G -- Start visualizing like a mofo
> isCM H -- once user ends session, they can do stuff with the output
> K = visualize H -- then visualize the output
> isCM K -- wash rinse and repeat
> closePort("") -- User closes port at the end.

This only works on the `server-workflow` branch feel free to checkout the branch and check it out.

**Comment by bbarwick** [comment]
@b-stone This looks good.  My only question is what happens if the user forgets to open the port and then does H = visualize G?  Does it store H as a method?  Also, what happens if the user forgets to close the port before they close M2?  Does it stay open until the computer is restarted?  Does M2 give an error message if the user tries to open port 8000 while it's already open?  Also, when you say "checkout the brach," is that the same as "clone the branch"?  I'm not sure if there is a different git command I should learn.

**Comment by b-stone** [comment]
To checkout the branch use `git checkout server-workflow`. This should somehow change your files on your computer into my files (I still don't understand this). To make sure it worked, do `git branch`.  To switch back, just do `git checkout bbarwickTest` or `git checkout master`. 

As to your questions, my understanding is that when M2 restarts, so does the server. This seems to be true in experimentation. However, if the server is not closed and neither is M2, then the port stays open. 

Yes you get an error is if port 8000 is open and you try to open it. This is one of the reasons I like having the user open the port. They can just find the one that works, then use that port for the entire M2 session.

**Comment by b-stone** [comment]
Once the user defines the port number, I need to create a way for the browser to know this number. 

One way to do this is for the template to have a variable and have M2 place the value there when the template is created.

**Comment by b-stone** [comment]
The user can now use any port (it used to be that user could only use port 8000). There is a slight change in syntax. For the open port method, the input string is just a number without a `$:` in front of it.

**Comment by b-stone** [comment]
The user can now only open one port at a time using `openPort()`. If a port is open and the user tries to open another one, an error pops up and explains the issue. I have also tested the ports with a network utility; when M2 is closed, the ports are also closed. The only way for the user to have a port open is if they open a port and leave M2 running.

**Comment by b-stone** [comment]
So I think I have finished the workflow for the server communication on the M2 side.  Here is the new workflow:

> restart
> loadPackage"Visualize"
> openPort "8080"
> G = graph({{0,1},{0,3},{0,4},{1,3},{2,3}},Singletons => {5})
> H = visualize (G, Verbose => true)
> isCM H
> K = visualize H
> isCM K
> closePort()

I now need to make it nice in the template and js files.
