### ISSUE TITLE
Create visualize method to overload each data type

### ISSUE THREAD

**Issue by b-stone** [b-stone/Visualize-M2#22]
The idea is to have one method that will call all data types. This would be really cool.

**Comment by b-stone** [comment]
@bbarwick , did you do this already?

**Comment by bbarwick** [comment]
This has been done for all current methods.  We just need to decide on the best ways to represent parameterized and implicitly defined curves and surfaces and what types of data should be passed for these methods.  For example, should visualize (x^2+y^2-9) return a graph of the circle x^2+y^2=9 in the plane?  Should it return a graph of the surface z = x^2+y^2-9?  How will the method determine this?

**Comment by b-stone** [comment]
We have decided to not work on parameterized curves. If we decide to work on this later we can reopen the issue.
