### ISSUE TITLE
What about collapsible sections in the menu?

### ISSUE THREAD

**Issue by b-stone** [b-stone/Visualize-M2#47]
I think it would be nice to have a multi-level menu. The idea I have in mind is for the main menu to have a couple of major functions (edit graph, export tikz, end session,...), and the rest be classes of functions. For example, we could have a menu item as 'Parity Tests'. When the user clicks this, the button expands to show the possible parity tests. Another button might be 'Numerical Invariants' (I.e. chromatic number, clique number, etc.). What do you think @bbarwick ?

**Comment by bbarwick** [comment]
I think this would be a good design idea, but I'm not sure how difficult it would be from a technical standpoint.  Maybe @vlandham could weigh in?

**Comment by vlandham** [comment]
the thing we are using for that side menu seems to be able to do sub-menus
pretty easy. albeit perhaps not in the format you want.

check out:
http://www.jqueryscript.net/demo/Sliding-Side-Menu-Panel-with-jQuery-Bootstrap-BootSideMenu/

if you click on 'sub menu test' you can see the sub menu system. we could
definitely use this as is - or try to format it differently.

**Comment by bbarwick** [comment]
This looks pretty good:

[Collapsible menus](http://www.w3schools.com/bootstrap/bootstrap_collapse.asp)

Check out accordion style.

**Comment by bbarwick** [comment]
Collapsible menus added in visGraph_brett branch using bootstrap.  Will merge soon and we can use the same formatting for the menus when visualizing other objects.
