### ISSUE TITLE
Ideal for 3d needs a make over

### ISSUE THREAD

**Issue by b-stone** [b-stone/Visualize-M2#87]
Lots of work needs to be done here. We need to clean up the code and place the menu on it.

**Comment by tenkosky** [comment]
I put the side menu in but it only has the key for the axes and it shows the generators.  I had to add a few lines to the visualize.m2 file to be able to output the generators of the ideal.  Feel free to change it if you want.

**Comment by b-stone** [comment]
Looks good. we need to create separate issues for things that need to be done for these ideals.
