### ISSUE TITLE
Add "Export to TikZ" functionality for Graphs.m2

### ISSUE THREAD

**Issue by bbarwick** [b-stone/Visualize-M2#9]
We would like to give the user the ability, once they have arranged the nodes and edges the way they like, to export the graph as a tikzpicture.  It may make sense to arrange the node coordinates in TikZ relative to the centroid of the graph nodes.  The tikzpicture code should also include any relevant node/edge labels, if the user has them set as viewable in the browser window.

**Comment by b-stone** [comment]
I am going to check to see how `Graphs.m2` does this and try to implement it.

**Comment by b-stone** [comment]
`Graphs.m2` needs a third party to do TikZ. I am looking into Gwyn's code for this. I added it to the repo.

**Comment by b-stone** [comment]
It turns out that this is annoying. For some reason the html understands `nodes` but but not `links`. I am looking at the this file:

`Visualize-M2/Visualize/templates/visGraph/visGraph-template.html`

**Comment by b-stone** [comment]
This is somewhat implemented. As long as the TikZ code is less than 2000 characters I have the export tikz button working. It currently throws an error if the characters exceed the limit. It would be nice to figure out a way to let the user copy all of the text no matter what the character size. 

When you click the button to export tikz in `Visualize-M2/Visualize/templates/visGraph/visGraph-template.html`, it calls the following function in `Visualize-M2/Visualize/visGraph2D.js`. I would like the user to be able to copy the text `tikzTex`.

function exportTikz (){
  var points = [];
  for(var i = 0; i < nodes.length; i++){
    points[i] = [nodes[i].x.toString()+"/"+nodes[i].y.toString()+"/"+nodes[i].id+"/"+nodes[i].name];
  }

  var edges = [];
  for(var j = 0; j < links.length; j++){
    edges[j] = [ links[j].source.id.toString()+"/"+links[j].target.id.toString() ];
  }

  var tikzTex = "";
  tikzTex =  "\\begin{tikzpicture}\n          % Point set in the form x-coord/y-coord/node ID/node label\n          \\newcommand*\\points{"+points+"}\n          % Edge set in the form Source ID/Target ID\n          \\newcommand*\\edges{"+edges+"}\n          % Scale to make the picture able to be viewed on the page\n          \\newcommand*\\scale{0.02}\n          % Creates nodes\n          \\foreach \\x/\\y/\\z/\\w in \\points {\n          \\node (\\z) at (\\scale*\\x,-\\scale*\\y) [circle,draw] {$\\w$};\n          }\n          % Creates egdes\n          \\foreach \\x/\\y in \\edges {\n          \\draw (\\x) -- (\\y);\n          }\n      \\end{tikzpicture}";

// <textarea id = "tikzTextArea">tikzTex</textarea>;

//  var tikzTextArea = document.getElementById(tikzTex);
//  tikzTextArea.select().focus();
//  $('#container').append('To copy emails to clipboard, press: Ctrl+C, then Enter <br />  <textarea id="tikzTex">'+tikzTex+'</textarea>');
//  $('#tikzTex').select().focus();
console.log(tikzTex.length);
  if (tikzTex.length < 2001){
    window.prompt("Copy this text the best way you can.", tikzTex );
  } else {
    alert("Feeling ambitious? Your TikZ code is "+tikzTex.length.toString()+" characters. The maximum amount of characters is 2000.");
  }
}

**Comment by b-stone** [comment]
I moved the above comment to Issue #27. This this issue is only concerned with creating the appropriote TikZ code and sending the information to the server. Making it look nice is @vlandham's job.

We might have to make separate functions for each data type. For instance, we might want to rename `exportTikz` to `exportGraphTikz`.

**Comment by bbarwick** [comment]
We will have to have somewhat different `exportTikz` methods for each data type, but we don't necessarily have to rename them in each template.  The method can still be called `exportTikz` in visDigraph2d.js, for example, with slightly different code just implementing the directed edges and loops in TikZ.

**Comment by b-stone** [comment]
This is a good observation and makes life a bit easier. As to the Graphs stuff, I think I would like to make the export as close to the actual image as possible. This is mainly because I felt that during our presentation in Boise, people wanted the TikZ of what they were seeing. This should not be too hard, just annoying. I can work on this.

**Comment by b-stone** [comment]
I left it in black and white. I think this issue is done. If we want exactly like the image in the browser, then I will start a new issue. But for now I think this is closed. 

Just to note, I made some random definitions in the LaTeX so that we would not overwrite user commands.
