### ISSUE TITLE
bring visSimplicialComplex up to code.

### ISSUE THREAD

**Issue by b-stone** [b-stone/Visualize-M2#99]
The simplicial complex code needs a lot of work. I have added the menu but there are many things that needs fixing.

**Comment by b-stone** [comment]
Oh my god who wrote this file?

**Comment by b-stone** [comment]
So I have the `restart` function working and I think `mouseover`. Also, `Reset Nodes` seams to be working. I am having an issue that I hope @bbarwick can help out with. There is a orange dot at the top left of the canvas, I remember having this problem earlier. How was it fixed?

**Comment by bbarwick** [comment]
The code is not perfect, but is now good enough to pass (lax) government inspection... see pull request #105.
